
# Consolidate Root (old, disabled)
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

# Route all pub URLs to the single master app
[[redirects]]
  from = "/pubs/*"
  to = "/app/index.html"
  status = 200

